site_name: Tupy Docs
theme:
  name: readthedocs
nav:
  - Introdução: index.md
  - Instalação: instalacao.md
  - Primeiro exemplo: exemplo.md
  - Interface: interface.md
  - Guia:
    - Imagens: imagens.md
    - Atualização: atualizacao.md
    - Teclado e mouse: entrada.md
    - Entrada e saída de texto: es.md
    - Outros tipos de objetos: classes.md
    - Encapsulamento: encapsulamento.md
    - BaseTupyObject: tupyobject.md
    - Grupos de objetos: grupos.md
